services:
  node:
    dns:
      - 8.8.8.8
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./:/app:cached
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    # Added --host 0.0.0.0 and --disable-host-check
    command: >
      sh -c "
        npm set fetch-timeout 60000 &&
        npm set fetch-retries 2 &&
        npm install -g @angular/cli &&
        npm install &&
        npm run dev -- --host 0.0.0.0 --poll=2000
      "

volumes:
  node_modules:

networks:
  default:
    driver: bridge