/**
 * @file Defines the structured input and output schemas for AI interactions.
 * These interfaces represent the desired format for data sent to and received from LLMs.
 */

// import { Task } from '../../core/services/task.service';

/**
 * Represents the structured input provided by the user to the AI for analysis or planning.
 */
export interface GoalInput {
  description: string;
  desiredOutcome: string;
  timeframe?: string; // e.g., "next 3 months", "by end of year"
  contextTaskIds?: string[]; // IDs of existing tasks relevant to the goal
}

/**
 * Represents a structured milestone generated by the AI as part of a plan.
 */
export interface MilestoneOutput {
  id: string;
  title: string;
  description?: string;
  deadline?: string; // ISO date string
  associatedTaskIds?: string[]; // IDs of tasks that contribute to this milestone
}

/**
 * Represents a structured task generated by the AI.
 * This is a simplified version of the core Task interface, focusing on AI-relevant fields.
 */
export interface TaskOutput {
  id: string;
  title: string;
  description?: string;
  category?: 'Super Important' | 'Important' | 'Less Important';
  project?: string;
  deadline?: string; // ISO date string
  estimatedEffort?: string; // e.g., "2h 30m"
  energyLevel?: 'High' | 'Medium' | 'Low';
  tags?: string[];
  subtasks?: {
    title: string;
    description?: string;
    notes?: string;
  }[]; // Updated subtask structure
}

/**
 * Represents a comprehensive plan generated by the AI.
 */
export interface PlanOutput {
  goal: string; // The original goal description
  overview: string; // A summary of the plan
  milestones: MilestoneOutput[];
  tasks: TaskOutput[];
  suggestedNextSteps?: string[];
}

/**
 * Represents a structured reflection or analysis generated by the AI.
 */
export interface ReflectionOutput {
  summary: string;
  keyLearnings?: string[];
  areasForImprovement?: string[];
  actionableInsights?: string[];
  sentiment?: 'Positive' | 'Neutral' | 'Negative';
}